name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Use node.js version 18
        uses: actions/setup-node
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build --prefix client
